namespace Vega
open Fable.Core

type NamedColor =  
  | [<CompiledName("black")>]  Black
  | [<CompiledName("silver")>]  Silver
  | [<CompiledName("gray")>] Gray
  | [<CompiledName("white")>] White
  | [<CompiledName("maroon")>] Maroon
  | [<CompiledName("red")>] Red
  | [<CompiledName("purple")>] Purple
  | [<CompiledName("fuchsia")>] Fuchsia
  | [<CompiledName("green")>] Green
  | [<CompiledName("lime")>] Lime
  | [<CompiledName("olive")>] Olive
  | [<CompiledName("yellow")>] Yellow
  | [<CompiledName("navy")>] Navy
  | [<CompiledName("blue")>] Blue
  | [<CompiledName("teal")>] Teal
  | [<CompiledName("aqua")>] Aqua
  | [<CompiledName("orange")>] Orange
  | [<CompiledName("aliceblue")>] Aliceblue
  | [<CompiledName("antiquewhite")>] Antiquewhite
  | [<CompiledName("aquamarine")>] Aquamarine
  | [<CompiledName("azure")>] Azure
  | [<CompiledName("beige")>] Beige
  | [<CompiledName("bisque")>] Bisque
  | [<CompiledName("blanchedalmond")>] Blanchedalmond
  | [<CompiledName("blueviolet")>] Blueviolet
  | [<CompiledName("brown")>] Brown
  | [<CompiledName("burlywood")>] Burlywood
  | [<CompiledName("cadetblue")>] Cadetblue
  | [<CompiledName("chartreuse")>] Chartreuse
  | [<CompiledName("chocolate")>] Chocolate
  | [<CompiledName("coral")>] Coral
  | [<CompiledName("cornflowerblue")>] Cornflowerblue
  | [<CompiledName("cornsilk")>] Cornsilk
  | [<CompiledName("crimson")>] Crimson
  | [<CompiledName("cyan")>] Cyan
  | [<CompiledName("darkblue")>] Darkblue
  | [<CompiledName("darkcyan")>] Darkcyan
  | [<CompiledName("darkgoldenrod")>] Darkgoldenrod
  | [<CompiledName("darkgray")>] Darkgray
  | [<CompiledName("darkgreen")>] Darkgreen
  | [<CompiledName("darkgrey")>] Darkgrey
  | [<CompiledName("darkkhaki")>] Darkkhaki
  | [<CompiledName("darkmagenta")>] Darkmagenta
  | [<CompiledName("darkolivegreen")>] Darkolivegreen
  | [<CompiledName("darkorange")>] Darkorange
  | [<CompiledName("darkorchid")>] Darkorchid
  | [<CompiledName("darkred")>] Darkred
  | [<CompiledName("darksalmon")>] Darksalmon
  | [<CompiledName("darkseagreen")>] Darkseagreen
  | [<CompiledName("darkslateblue")>] Darkslateblue
  | [<CompiledName("darkslategray")>] Darkslategray
  | [<CompiledName("darkslategrey")>] Darkslategrey
  | [<CompiledName("darkturquoise")>] Darkturquoise
  | [<CompiledName("darkviolet")>] Darkviolet
  | [<CompiledName("deeppink")>] Deeppink
  | [<CompiledName("deepskyblue")>] Deepskyblue
  | [<CompiledName("dimgray")>] Dimgray
  | [<CompiledName("dimgrey")>] Dimgrey
  | [<CompiledName("dodgerblue")>] Dodgerblue
  | [<CompiledName("firebrick")>] Firebrick
  | [<CompiledName("floralwhite")>] Floralwhite
  | [<CompiledName("forestgreen")>] Forestgreen
  | [<CompiledName("gainsboro")>] Gainsboro
  | [<CompiledName("ghostwhite")>] Ghostwhite
  | [<CompiledName("gold")>] Gold
  | [<CompiledName("goldenrod")>] Goldenrod
  | [<CompiledName("greenyellow")>] Greenyellow
  | [<CompiledName("grey")>] Grey
  | [<CompiledName("honeydew")>] Honeydew
  | [<CompiledName("hotpink")>] Hotpink
  | [<CompiledName("indianred")>] Indianred
  | [<CompiledName("indigo")>] Indigo
  | [<CompiledName("ivory")>] Ivory
  | [<CompiledName("khaki")>] Khaki
  | [<CompiledName("lavender")>] Lavender
  | [<CompiledName("lavenderblush")>] Lavenderblush
  | [<CompiledName("lawngreen")>] Lawngreen
  | [<CompiledName("lemonchiffon")>] Lemonchiffon
  | [<CompiledName("lightblue")>] Lightblue
  | [<CompiledName("lightcoral")>] Lightcoral
  | [<CompiledName("lightcyan")>] Lightcyan
  | [<CompiledName("lightgoldenrodyellow")>] Lightgoldenrodyellow
  | [<CompiledName("lightgray")>] Lightgray
  | [<CompiledName("lightgreen")>] Lightgreen
  | [<CompiledName("lightgrey")>] Lightgrey
  | [<CompiledName("lightpink")>] Lightpink
  | [<CompiledName("lightsalmon")>] Lightsalmon
  | [<CompiledName("lightseagreen")>] Lightseagreen
  | [<CompiledName("lightskyblue")>] Lightskyblue
  | [<CompiledName("lightslategray")>] Lightslategray
  | [<CompiledName("lightslategrey")>] Lightslategrey
  | [<CompiledName("lightsteelblue")>] Lightsteelblue
  | [<CompiledName("lightyellow")>] Lightyellow
  | [<CompiledName("limegreen")>] Limegreen
  | [<CompiledName("linen")>] Linen
  | [<CompiledName("magenta")>] Magenta
  | [<CompiledName("mediumaquamarine")>] Mediumaquamarine
  | [<CompiledName("mediumblue")>] Mediumblue
  | [<CompiledName("mediumorchid")>] Mediumorchid
  | [<CompiledName("mediumpurple")>] Mediumpurple
  | [<CompiledName("mediumseagreen")>] Mediumseagreen
  | [<CompiledName("mediumslateblue")>] Mediumslateblue
  | [<CompiledName("mediumspringgreen")>] Mediumspringgreen
  | [<CompiledName("mediumturquoise")>] Mediumturquoise
  | [<CompiledName("mediumvioletred")>] Mediumvioletred
  | [<CompiledName("midnightblue")>] Midnightblue
  | [<CompiledName("mintcream")>] Mintcream
  | [<CompiledName("mistyrose")>] Mistyrose
  | [<CompiledName("moccasin")>] Moccasin
  | [<CompiledName("navajowhite")>] Navajowhite
  | [<CompiledName("oldlace")>] Oldlace
  | [<CompiledName("olivedrab")>] Olivedrab
  | [<CompiledName("orangered")>] Orangered
  | [<CompiledName("orchid")>] Orchid
  | [<CompiledName("palegoldenrod")>] Palegoldenrod
  | [<CompiledName("palegreen")>] Palegreen
  | [<CompiledName("paleturquoise")>] Paleturquoise
  | [<CompiledName("palevioletred")>] Palevioletred
  | [<CompiledName("papayawhip")>] Papayawhip
  | [<CompiledName("peachpuff")>] Peachpuff
  | [<CompiledName("peru")>] Peru
  | [<CompiledName("pink")>] Pink
  | [<CompiledName("plum")>] Plum
  | [<CompiledName("powderblue")>] Powderblue
  | [<CompiledName("rosybrown")>] Rosybrown
  | [<CompiledName("royalblue")>] Royalblue
  | [<CompiledName("saddlebrown")>] Saddlebrown
  | [<CompiledName("salmon")>] Salmon
  | [<CompiledName("sandybrown")>] Sandybrown
  | [<CompiledName("seagreen")>] Seagreen
  | [<CompiledName("seashell")>] Seashell
  | [<CompiledName("sienna")>] Sienna
  | [<CompiledName("skyblue")>] Skyblue
  | [<CompiledName("slateblue")>] Slateblue
  | [<CompiledName("slategray")>] Slategray
  | [<CompiledName("slategrey")>] Slategrey
  | [<CompiledName("snow")>] Snow
  | [<CompiledName("springgreen")>] Springgreen
  | [<CompiledName("steelblue")>] Steelblue
  | [<CompiledName("tan")>] Tan
  | [<CompiledName("thistle")>] Thistle
  | [<CompiledName("tomato")>] Tomato
  | [<CompiledName("turquoise")>] Turquoise
  | [<CompiledName("violet")>] Violet
  | [<CompiledName("wheat")>] Wheat
  | [<CompiledName("whitesmoke")>] Whitesmoke
  | [<CompiledName("yellowgreen")>] Yellowgreen
  | [<CompiledName("rebeccapurple")>] Rebeccapurple    
type Color = U2<NamedColor, string>
